#! /usr/bin/python2.7

# Copyright 2012 Jtmorgan

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import datetime
import hb_queries
import hb_templates
import hostbot_settings
import MySQLdb
from warnings import filterwarnings
import wikitools

def getNewbies(#query): #pass cursor, too?
	"""docstring goes here"""
	cursor.execute("get 10 edit newbie list")
# 	cursor.execute("get autoconfirmed newbie list")
	output = []
	fields = cursor.fetchall()
	for field in fields:
		number = field[0]
		user_name = unicode(field[1], 'utf-8')
		user_editcount = field[2]
		talk_page = '[[User_talk:%s|%s]]' % (user_name, user_name)
		user_contribs = '[[Special:Contributions/%s|contribs]]' % user_name
		#put table row in templates class
		table_row = u'''| %d
	| %s
	| %d
	| %s
	|
	|-''' % (number, talk_page, user_editcount, user_contribs)
		output.append(table_row)
	return output	

def makeReport(10edit_rows, autoconfirmed_rows):
	wiki = wikitools.Wiki(hostbot_settings.apiurl)
	wiki.login(hostbot_settings.username, hostbot_settings.password)
	report_title = hostbot_settings.rootpage + '/Hosts/Database_reports#Daily_Report'
	report_template = #fixme	
	report = wikitools.Page(wiki, report_title)
	report_text = report_template % ('\n'.join(10edit_rows), '\n'.join(autoconfirmed_rows))
	report_text = report_text.encode('utf-8')
	report.edit(report_text, section=1, summary="Automatic daily invitee report generated by [[User:HostBot|HostBot]].", bot=1) #put this in the output settings file

##MAIN##
conn = MySQLdb.connect(host = hostbot_settings.host, db = hostbot_settings.dbname, read_default_file = hostbot_settings.defaultcnf, use_unicode=1, charset="utf8")
cursor = conn.cursor()
filterwarnings('ignore', category = MySQLdb.Warning)
queries = hb_queries.Query()
templates = hb_queries.Query() #fixme

10edit_rows = getNewbies(#query here) #builds output list for 10-edit newbies
autoconfirmed_rows = getNewbies(#query here) #builds output list for autoconfirmed users
makeReport(10edit_rows, autoconfirmed_rows)

cursor.close()
conn.close()


